import type { Metadata } from 'next'
import NavBar from '@/components/navBar'
import Footer from '@/components/footer'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
  title: 'Dois marcos',
  description: 'Generated by create next app',
  authors: { name: 'André', url: 'https://ae.dev.br/' },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies().get('token')?.value
  return (
    <div className="flex flex-col min-h-screen">
      {cookieStore && <NavBar />}
      <div className="flex-grow">{children}</div>
      {cookieStore && <Footer />}
    </div>
  )
}
